export enum RoutersEnum {
  app = 'app',
  login = 'login',
  register = 'register',
  recovery = 'recovery-password',
  terms = 'terms-of-use',
  phoneConfirm = 'phone-confirm',
  emailConfirm = 'email-confirm',
  home = 'home',
  events = 'events',
  areas = 'areas',
  warehouses = 'warehouses',
  materials = 'materials',
  members = 'members',
}
